# Se metti True, ti invia TUTTE le CVE (te lo sconsiglio, sono troppe)
ALL_VALID: False

# Parole chiave da cercare nella descrizione (Case Insensitive)
DESCRIPTION_KEYWORDS_I:
  - "fortinet"
  - "fortios"
  - "forticlient"
  - "fortigate"
  - "fortiproxy"
  - "privilege escalation"
  - "remote code execution"

# Parole chiave esatte (Case Sensitive)
DESCRIPTION_KEYWORDS:
  - "Fortinet"
  - "FortiGate"

# Parole chiave da cercare nel campo "Product"
PRODUCT_KEYWORDS_I:
  - "fortinet"
  - "fortios"
  - "forticlient"

PRODUCT_KEYWORDS:
  - "fortinet"
